#include "items.h"

// There are four major pools that the filler uses: dungeon, advancement,
// nice-to-have, and trash. Each of these will have a static array definition
// because we're only caring about open mode.

int DUNGEON_ITEMS[] = {
    Items::BigKeyA2,  Items::BigKeyD1,  Items::BigKeyD2,  Items::BigKeyD3,
    Items::BigKeyD4,  Items::BigKeyD5,  Items::BigKeyD6,  Items::BigKeyD7,
    Items::BigKeyP1,  Items::BigKeyP2,  Items::BigKeyP3,

    Items::KeyA2,     Items::KeyA2,     Items::KeyA2,     Items::KeyA2,
    Items::KeyD1,     Items::KeyD1,     Items::KeyD1,     Items::KeyD1,
    Items::KeyD1,     Items::KeyD1,     Items::KeyD2,     Items::KeyD3,
    Items::KeyD3,     Items::KeyD4,     Items::KeyD5,     Items::KeyD5,
    Items::KeyD6,     Items::KeyD6,     Items::KeyD6,     Items::KeyD7,
    Items::KeyD7,     Items::KeyD7,     Items::KeyD7,     Items::KeyA1,
    Items::KeyA1,     Items::KeyH2,     Items::KeyP2,     Items::KeyP3,

    Items::MapA2,     Items::MapD1,     Items::MapD2,     Items::MapD3,
    Items::MapD4,     Items::MapD5,     Items::MapD6,     Items::MapD7,
    Items::MapH2,     Items::MapP1,     Items::MapP2,     Items::MapP3,

    Items::CompassA2, Items::CompassD1, Items::CompassD2, Items::CompassD3,
    Items::CompassD4, Items::CompassD5, Items::CompassD6, Items::CompassD7,
    Items::CompassP1, Items::CompassP2, Items::CompassP3,
};

// Advancement items should contains 2 progressive swords. The other two
// swords go in the nice-to-have category. SilverArrowUpgrade is in nice
// items.

int ADVANCEMENT_ITEMS[] = {
    Items::Bombos,
    Items::BookOfMudora,
    Items::Bottle,
    Items::Bow,
    Items::BugCatchingNet,
    Items::CaneOfByrna,
    Items::CaneOfSomaria,
    Items::Cape,
    Items::Ether,
    Items::FireRod,
    Items::Flippers,
    Items::HalfMagic,
    Items::Hammer,
    Items::Hookshot,
    Items::IceRod,
    Items::Lamp,
    Items::MagicMirror,
    Items::MoonPearl,
    Items::Mushroom,
    Items::OcarinaInactive,
    Items::PegasusBoots,
    Items::Powder,
    Items::ProgressiveGlove,
    Items::ProgressiveGlove,
    Items::ProgressiveShield,
    Items::ProgressiveShield,
    Items::ProgressiveShield,
    Items::ProgressiveSword,
    Items::ProgressiveSword,
    Items::Quake,
    Items::Shovel,
    Items::SilverArrowUpgrade,
};

int NICE_ITEMS[] = {
    Items::Bottle,
    Items::Bottle,
    Items::Bottle,

    Items::ProgressiveSword,
    Items::ProgressiveSword,

    Items::HeartContainer,
    Items::BossHeartContainer,
    Items::BossHeartContainer,
    Items::BossHeartContainer,
    Items::BossHeartContainer,
    Items::BossHeartContainer,
    Items::BossHeartContainer,
    Items::BossHeartContainer,
    Items::BossHeartContainer,
    Items::BossHeartContainer,
    Items::BossHeartContainer,

    Items::ProgressiveArmor,
    Items::ProgressiveArmor,

    Items::Boomerang,
    Items::RedBoomerang,
};

int TRASH_ITEMS[] = {
    Items::PieceOfHeart,
    Items::PieceOfHeart,
    Items::PieceOfHeart,
    Items::PieceOfHeart,
    Items::PieceOfHeart,
    Items::PieceOfHeart,
    Items::PieceOfHeart,
    Items::PieceOfHeart,
    Items::PieceOfHeart,
    Items::PieceOfHeart,
    Items::PieceOfHeart,
    Items::PieceOfHeart,
    Items::PieceOfHeart,
    Items::PieceOfHeart,
    Items::PieceOfHeart,
    Items::PieceOfHeart,
    Items::PieceOfHeart,
    Items::PieceOfHeart,
    Items::PieceOfHeart,
    Items::PieceOfHeart,
    Items::PieceOfHeart,
    Items::PieceOfHeart,
    Items::PieceOfHeart,
    Items::PieceOfHeart,

    Items::BombUpgrade5,
    Items::BombUpgrade5,
    Items::BombUpgrade5,
    Items::BombUpgrade5,
    Items::BombUpgrade5,
    Items::BombUpgrade5,

    Items::BombUpgrade10,

    Items::ArrowUpgrade5,
    Items::ArrowUpgrade5,
    Items::ArrowUpgrade5,
    Items::ArrowUpgrade5,
    Items::ArrowUpgrade5,
    Items::ArrowUpgrade5,

    Items::ArrowUpgrade10,

    Items::Arrow,

    Items::TenArrows,
    Items::TenArrows,
    Items::TenArrows,
    Items::TenArrows,
    Items::TenArrows,

    Items::ThreeBombs,
    Items::ThreeBombs,
    Items::ThreeBombs,
    Items::ThreeBombs,
    Items::ThreeBombs,
    Items::ThreeBombs,
    Items::ThreeBombs,
    Items::ThreeBombs,
    Items::ThreeBombs,
    Items::ThreeBombs,

    Items::OneRupee,
    Items::OneRupee,

    Items::FiveRupees,
    Items::FiveRupees,
    Items::FiveRupees,
    Items::FiveRupees,

    Items::TwentyRupees,
    Items::TwentyRupees,
    Items::TwentyRupees,
    Items::TwentyRupees,
    Items::TwentyRupees,
    Items::TwentyRupees,
    Items::TwentyRupees,
    Items::TwentyRupees,
    Items::TwentyRupees,
    Items::TwentyRupees,
    Items::TwentyRupees,
    Items::TwentyRupees,
    Items::TwentyRupees,
    Items::TwentyRupees,
    Items::TwentyRupees,
    Items::TwentyRupees,
    Items::TwentyRupees,
    Items::TwentyRupees,
    Items::TwentyRupees,
    Items::TwentyRupees,
    Items::TwentyRupees,
    Items::TwentyRupees,
    Items::TwentyRupees,
    Items::TwentyRupees,
    Items::TwentyRupees,
    Items::TwentyRupees,
    Items::TwentyRupees,
    Items::TwentyRupees,

    Items::FiftyRupees,
    Items::FiftyRupees,
    Items::FiftyRupees,
    Items::FiftyRupees,
    Items::FiftyRupees,
    Items::FiftyRupees,
    Items::FiftyRupees,

    Items::OneHundredRupees,

    Items::ThreeHundredRupees,
    Items::ThreeHundredRupees,
    Items::ThreeHundredRupees,
    Items::ThreeHundredRupees,
    Items::ThreeHundredRupees,
};
