#include "items.h"

// There are four major pools that the filler uses: dungeon, advancement,
// nice-to-have, and trash. Each of these will have a static array definition
// because we're only caring about open mode.

Item DUNGEON_ITEMS[] = {
    Item::BigKeyA2,  Item::BigKeyD1,  Item::BigKeyD2,  Item::BigKeyD3,
    Item::BigKeyD4,  Item::BigKeyD5,  Item::BigKeyD6,  Item::BigKeyD7,
    Item::BigKeyP1,  Item::BigKeyP2,  Item::BigKeyP3,

    Item::KeyA2,     Item::KeyA2,     Item::KeyA2,     Item::KeyA2,
    Item::KeyD1,     Item::KeyD1,     Item::KeyD1,     Item::KeyD1,
    Item::KeyD1,     Item::KeyD1,     Item::KeyD2,     Item::KeyD3,
    Item::KeyD3,     Item::KeyD4,     Item::KeyD5,     Item::KeyD5,
    Item::KeyD6,     Item::KeyD6,     Item::KeyD6,     Item::KeyD7,
    Item::KeyD7,     Item::KeyD7,     Item::KeyD7,     Item::KeyA1,
    Item::KeyA1,     Item::KeyH2,     Item::KeyP2,     Item::KeyP3,

    Item::MapA2,     Item::MapD1,     Item::MapD2,     Item::MapD3,
    Item::MapD4,     Item::MapD5,     Item::MapD6,     Item::MapD7,
    Item::MapH2,     Item::MapP1,     Item::MapP2,     Item::MapP3,

    Item::CompassA2, Item::CompassD1, Item::CompassD2, Item::CompassD3,
    Item::CompassD4, Item::CompassD5, Item::CompassD6, Item::CompassD7,
    Item::CompassP1, Item::CompassP2, Item::CompassP3,
};

// Advancement items should contains 2 progressive swords. The other two
// swords go in the nice-to-have category. SilverArrowUpgrade is in nice
// items.

Item ADVANCEMENT_ITEMS[] = {
    Item::Bombos,
    Item::BookOfMudora,
    Item::Bottle,
    Item::Bow,
    Item::BugCatchingNet,
    Item::CaneOfByrna,
    Item::CaneOfSomaria,
    Item::Cape,
    Item::Ether,
    Item::FireRod,
    Item::Flippers,
    Item::HalfMagic,
    Item::Hammer,
    Item::Hookshot,
    Item::IceRod,
    Item::Lamp,
    Item::MagicMirror,
    Item::MoonPearl,
    Item::Mushroom,
    Item::OcarinaInactive,
    Item::PegasusBoots,
    Item::Powder,
    Item::ProgressiveGlove,
    Item::ProgressiveGlove,
    Item::ProgressiveShield,
    Item::ProgressiveShield,
    Item::ProgressiveShield,
    Item::ProgressiveSword,
    Item::ProgressiveSword,
    Item::Quake,
    Item::Shovel,
    Item::SilverArrowUpgrade,
};

Item NICE_ITEMS[] = {
    Item::Bottle,
    Item::Bottle,
    Item::Bottle,

    Item::ProgressiveSword,
    Item::ProgressiveSword,

    Item::HeartContainer,
    Item::BossHeartContainer,
    Item::BossHeartContainer,
    Item::BossHeartContainer,
    Item::BossHeartContainer,
    Item::BossHeartContainer,
    Item::BossHeartContainer,
    Item::BossHeartContainer,
    Item::BossHeartContainer,
    Item::BossHeartContainer,
    Item::BossHeartContainer,

    Item::ProgressiveArmor,
    Item::ProgressiveArmor,

    Item::Boomerang,
    Item::RedBoomerang,
};

Item TRASH_ITEMS[] = {
    Item::PieceOfHeart,
    Item::PieceOfHeart,
    Item::PieceOfHeart,
    Item::PieceOfHeart,
    Item::PieceOfHeart,
    Item::PieceOfHeart,
    Item::PieceOfHeart,
    Item::PieceOfHeart,
    Item::PieceOfHeart,
    Item::PieceOfHeart,
    Item::PieceOfHeart,
    Item::PieceOfHeart,
    Item::PieceOfHeart,
    Item::PieceOfHeart,
    Item::PieceOfHeart,
    Item::PieceOfHeart,
    Item::PieceOfHeart,
    Item::PieceOfHeart,
    Item::PieceOfHeart,
    Item::PieceOfHeart,
    Item::PieceOfHeart,
    Item::PieceOfHeart,
    Item::PieceOfHeart,
    Item::PieceOfHeart,

    Item::BombUpgrade5,
    Item::BombUpgrade5,
    Item::BombUpgrade5,
    Item::BombUpgrade5,
    Item::BombUpgrade5,
    Item::BombUpgrade5,

    Item::BombUpgrade10,

    Item::ArrowUpgrade5,
    Item::ArrowUpgrade5,
    Item::ArrowUpgrade5,
    Item::ArrowUpgrade5,
    Item::ArrowUpgrade5,
    Item::ArrowUpgrade5,

    Item::ArrowUpgrade10,

    Item::Arrow,

    Item::TenArrows,
    Item::TenArrows,
    Item::TenArrows,
    Item::TenArrows,
    Item::TenArrows,

    Item::ThreeBombs,
    Item::ThreeBombs,
    Item::ThreeBombs,
    Item::ThreeBombs,
    Item::ThreeBombs,
    Item::ThreeBombs,
    Item::ThreeBombs,
    Item::ThreeBombs,
    Item::ThreeBombs,
    Item::ThreeBombs,

    Item::OneRupee,
    Item::OneRupee,

    Item::FiveRupees,
    Item::FiveRupees,
    Item::FiveRupees,
    Item::FiveRupees,

    Item::TwentyRupees,
    Item::TwentyRupees,
    Item::TwentyRupees,
    Item::TwentyRupees,
    Item::TwentyRupees,
    Item::TwentyRupees,
    Item::TwentyRupees,
    Item::TwentyRupees,
    Item::TwentyRupees,
    Item::TwentyRupees,
    Item::TwentyRupees,
    Item::TwentyRupees,
    Item::TwentyRupees,
    Item::TwentyRupees,
    Item::TwentyRupees,
    Item::TwentyRupees,
    Item::TwentyRupees,
    Item::TwentyRupees,
    Item::TwentyRupees,
    Item::TwentyRupees,
    Item::TwentyRupees,
    Item::TwentyRupees,
    Item::TwentyRupees,
    Item::TwentyRupees,
    Item::TwentyRupees,
    Item::TwentyRupees,
    Item::TwentyRupees,
    Item::TwentyRupees,

    Item::FiftyRupees,
    Item::FiftyRupees,
    Item::FiftyRupees,
    Item::FiftyRupees,
    Item::FiftyRupees,
    Item::FiftyRupees,
    Item::FiftyRupees,

    Item::OneHundredRupees,

    Item::ThreeHundredRupees,
    Item::ThreeHundredRupees,
    Item::ThreeHundredRupees,
    Item::ThreeHundredRupees,
    Item::ThreeHundredRupees,
};
